Repository beyond-sw-camp/be08-fin-200OK-CONCENTRIC-frontend, pull requests merged in 2024-10, with the labels that each got.

#13 [Feat/#12] 로그인 로직
  package.json
  src/examples/Navbars/Navbar.vue
  src/main.js
  src/router/index.js
  src/store/user.js
  src/views/Signin.vue
Labels: Feat, Frontend

#15 [Feat/#12] 로그아웃 로직, bearer 토큰 확인
  package.json
  src/examples/Navbars/Navbar.vue
  src/main.js
  src/store/user.js
  src/views/Signin.vue
Labels: Feat, Frontend

#21 [Feat/#20] 채팅 페이지 구현
  package.json
  src/router/index.js
  src/views/Chat/ChatComponents/ChatFile.vue
  src/views/Chat/ChatComponents/ChatList.vue
  src/views/Chat/ChatComponents/ChatRoom.vue
  src/views/Chat/ChatComponents/ChatRoomTest.vue
  src/views/Chat/ChatView.vue
Labels: Feat, Frontend

#22 [Feat/#12] 로그인, 로그아웃, 회원가입 기능 완료
  src/assets/img/icons/expand_more_40dp_000000.png
  src/assets/img/sample_images/371754@2x.png
  src/assets/img/sample_images/371759@2x.png
  src/assets/img/sample_images/371772@2x.png
  src/router/index.js
  src/store/user.js
  src/types/vueperslides.d.ts
  src/views/Calender/MonthCalender.vue
  src/views/Navbar/Navbar.vue
  src/views/Sign/Signin.vue
  src/views/components/ContentsDropdown.vue
  src/views/components/ModalDeleteRow.vue
  src/views/components/MonthCalender.vue
  src/views/components/Pagination.vue
  src/views/components/Superman.vue
  src/views/components/superman.html
Labels: Feat, Frontend

#23 [Feat/#12] 회원가입 기능, 로그아웃 버튼
  src/views/Navbar/Navbar.vue
  src/views/Sign/Signin.vue
Labels: Feat, Frontend

#27 [Feat/#26] Axios Interceptor 추가
  src/main.js
  src/views/Navbar/Navbar.vue
  src/views/Sidenav/SidenavProfile.vue
Labels: Feat, Frontend

#28 [Feat/#25] Navbar 알림 기능
  src/assets/img/koongya.png
  src/main.js
  src/views/Navbar/Navbar.vue
Labels: Feat, Frontend

#32 [Feat/#20] 친구 목록 추가, 개인 채팅방 생성, 파일 관련
  src/views/Chat/ChatComponents/ChatFile.vue
  src/views/Chat/ChatComponents/ChatList.vue
  src/views/Chat/ChatComponents/ChatRoom.vue
  src/views/Chat/ChatComponents/ChatRoomDetails.vue
  src/views/Chat/ChatView.vue
Labels: Feat, Frontend

#37 [Feat/#29] social logic
  src/App.vue
  src/main.js
  src/router/index.js
  src/store/states.js
  src/views/Navbar/Navbar.vue
  src/views/PageCustom/Social.vue
  src/views/Sidenav/SidenavIndex.vue
  src/views/Sign/Signin.vue
  src/views/Sign/Signup.vue
Labels: Feat, Fix, Frontend, Refactoring

#39 [Feat/#33] 채팅 알림 기능 구현
  src/App.vue
  src/store/notification.js
  src/views/Chat/ChatComponents/ChatList.vue
  src/views/Chat/ChatComponents/ChatNotification.vue
  src/views/Chat/ChatComponents/ChatRoom.vue
  src/views/Chat/ChatView.vue
Labels: Feat, Frontend

#40 [Feat/#20] 채팅 컴포넌트 사이드바로 이주
  src/App.vue
  src/router/index.js
  src/store/index.js
  src/views/Chat/ChatComponents/ChatFile.vue
  src/views/Chat/ChatComponents/ChatList.vue
  src/views/Chat/ChatComponents/ChatNotification.vue
  src/views/Chat/ChatComponents/ChatRoom.vue
  src/views/Chat/ChatView.vue
Labels: Feat, Frontend, Refactoring

#41 [Feat/#38] 개인 파일함 다운로드 / 삭제 구현
  package.json
  src/App.vue
  src/router/index.js
  src/views/social/Social.vue
  src/views/storage/PrivateStorage.vue
Labels: Feat, Frontend

#44 [Feat/#38] 개인 파일함
  src/router/index.js
  src/views/storage/PrivateStorage.vue
  src/views/storage/UploadModal.vue
Labels: Feat, Frontend

#45 [Feat/#20] 채팅 req, res 수정, 파일 로직 수정
  src/views/Chat/ChatComponents/ChatFile.vue
  src/views/Chat/ChatComponents/ChatRoom.vue
Labels: Feat, Frontend

#47 [Feat/#46] 프로필 이미지 요청 로직
  src/views/Navbar/Navbar.vue
Labels: Feat, Frontend

#48 [Feat/#46] 마이페이지
  src/App.vue
  src/router/index.js
  src/store/states.js
  src/views/Navbar/Navbar.vue
  src/views/Profile/Profile.vue
  src/views/Profile/ProfileCard.vue
  src/views/Profile/ProfileEdit.vue
  src/views/Sidenav/SidenavIndex.vue
  src/views/notification/NotificationList.vue
  src/views/social/FriendList.vue
  src/views/social/Social.vue
  src/views/storage/PrivateStorage.vue
Labels: Feat, Frontend

#51 [Feat/#50] 채팅 이미지 로드, 알림 수정
  src/views/Chat/ChatComponents/ChatFile.vue
  src/views/Chat/ChatComponents/ChatList.vue
  src/views/Chat/ChatComponents/ChatRoom.vue
  src/views/Chat/ChatComponents/ChatRoomDetails.vue
  src/views/Chat/ChatView.vue
Labels: Feat, Frontend

#53 [Refactor/#50] 디렉토리 리팩토링
  src/App.vue
  src/assets/scss/argon-dashboard/_navbar-vertical.scss
  src/assets/scss/argon-dashboard/_variables.scss
  src/assets/scss/argon-dashboard/bootstrap/_navbar.scss
  src/assets/scss/argon-dashboard/bootstrap/_variables.scss
  src/assets/scss/argon-dashboard/variables/_navbar-vertical.scss
  src/assets/scss/argon-dashboard/variables/_navbar.scss
  src/etc/VirtualReality.vue
  src/examples/NavbarExample.vue
  src/router/index.js
  src/views/PageCustom/Configurator.vue
  src/views/chat/ChatView.vue
  src/views/chat/components/ChatFile.vue
  src/views/chat/components/ChatList.vue
  src/views/chat/components/ChatNotification.vue
  src/views/chat/components/ChatRoom.vue
  src/views/chat/components/ChatRoomDetails.vue
  src/views/mainpage/RightTopClock.vue
  src/views/mainpage/Tables.vue
  src/views/mainpage/components/AddSchedule.vue
  src/views/mainpage/components/Tasks.vue
  src/views/navbar/Navbar.vue
  src/views/profile/Profile.vue
  src/views/profile/ProfileCard.vue
  src/views/profile/ProfileEdit.vue
  src/views/sidenav/DropdownItems.vue
  src/views/sidenav/SidenavCard.vue
  src/views/sidenav/SidenavIndex.vue
  src/views/sidenav/SidenavItem.vue
  src/views/sidenav/SidenavList.vue
  src/views/sidenav/SidenavProfile.vue
  src/views/social/FriendList.vue
Labels: Feat, Frontend, Refactoring

#59 [Refactor/#58] 웹소켓 로직 변경, 채팅 로직 변경
  src/views/chat/ChatView.vue
  src/views/chat/components/ChatList.vue
  src/views/chat/components/ChatRoom.vue
Labels: Feat, Frontend, Refactoring

#60 [Feat/#46] 마이페이지
  src/components/ArgonComponents/ArgonInput.vue
  src/store/user.js
  src/views/profile/ProfileCard.vue
  src/views/profile/ProfileEdit.vue
Labels: Feat, Frontend

#64 [Feat/#63] 채팅 안읽음 뱃지 구현
  src/views/chat/ChatView.vue
  src/views/chat/components/ChatList.vue
Labels: Feat, Frontend

#65 [Feat/#46] 마이페이지 기능
  src/main.js
  src/router/index.js
  src/views/navbar/Navbar.vue
  src/views/profile/PasswordEdit.vue
  src/views/profile/Profile.vue
  src/views/profile/ProfileDeactivation.vue
  src/views/profile/ProfileEdit.vue
Labels: Feat, Frontend

#66 [Feat/#46] 마이페이지
  src/main.js
  src/views/navbar/Navbar.vue
  src/views/profile/PasswordEdit.vue
  src/views/profile/ProfileDeactivation.vue
Labels: Feat, Frontend

#71 [Feat/#20] 채팅 컴포넌트 애니메이션 적용
  src/App.vue
  src/views/chat/ChatView.vue
  src/views/chat/components/ChatFile.vue
  src/views/chat/components/ChatList.vue
  src/views/chat/components/ChatRoom.vue
  src/views/chat/components/ChatRoomDetails.vue
Labels: Feat, Frontend

#72 [Feat/#46] 프로필사진, 배경사진 기본값 설정, 친구 프로필 출력
  src/views/navbar/Navbar.vue
  src/views/profile/ProfileCard.vue
  src/views/profile/ProfileEdit.vue
  src/views/sign/Signin.vue
  src/views/social/FriendList.vue
  src/views/social/FriendProfile.vue
  src/views/storage/PrivateStorage.vue
  src/views/storage/UploadModal.vue
Labels: Feat, Frontend

#73 [Feat/#38] 파일함 기능
  src/main.js
  src/views/navbar/Navbar.vue
  src/views/profile/Profile.vue
  src/views/sign/Signin.vue
  src/views/storage/PrivateStorage.vue
Labels: Feat, Frontend, Refactoring

#76 [Feat/#74] 알림 기능
  src/views/navbar/Navbar.vue
  src/views/notification/NotificationList.vue
  src/views/storage/PrivateStorage.vue
Labels: Feat, Frontend

#79 [Feat/#29] 이미지 전달 방식 변경
  src/views/navbar/Navbar.vue
  src/views/profile/ProfileCard.vue
  src/views/profile/ProfileEdit.vue
  src/views/social/FriendList.vue
  src/views/social/FriendProfile.vue
Labels: Feat, Frontend, Refactoring

#83 [Feat/#29] 친구 기능
  src/store/states.js
  src/views/navbar/Navbar.vue
  src/views/notification/NotificationList.vue
  src/views/profile/Profile.vue
  src/views/social/AddFriend.vue
  src/views/social/FriendList.vue
  src/views/social/FriendRequest.vue
  src/views/social/Social.vue
Labels: Feat, Frontend

#86 [Feat/#74] 알림 삭제 트랜지션 추가
  src/store/states.js
  src/views/notification/NotificationList.vue
  src/views/storage/PrivateStorage.vue
Labels: Feat, Frontend

#87 [Fix/#85] 친구 리스트 이미지 불러오는 방식 변경
  src/views/chat/components/ChatList.vue
Labels: Fix, Frontend

#89 [Refactor/#88] 로그인 & 회원가입 페이지 수정완료
  src/views/sign/Signin.vue
Labels: Feat, Frontend, Refactoring

#96 [Feat] 팀 정보 수정, 삭제, 나가기 api 연결
  src/store/user.js
  src/views/sidenav/SidenavProfile.vue
  src/views/team/TeamPage.vue
  src/views/team/TeamProfile.vue
  src/views/team/TeamProfileEdit.vue
Labels: Frontend

#101 [Feat/#99] 레이아웃 수정
  src/App.vue
  src/assets/img/logos/logo.png
  src/examples/FooterExample.vue
  src/views/mainpage/Tables.vue
  src/views/mainpage/components/Tasks.vue
  src/views/navbar/Navbar.vue
  src/views/notification/NotificationList.vue
  src/views/profile/PasswordEdit.vue
  src/views/profile/Profile.vue
  src/views/profile/ProfileCard.vue
  src/views/profile/ProfileDeactivation.vue
  src/views/profile/ProfileEdit.vue
  src/views/sidenav/SidenavProfile.vue
  src/views/social/Social.vue
  src/views/storage/PrivateStorage.vue
  src/views/team/TeamProfile.vue
Labels: Feat, Frontend

#97 [Feat/#80] 팀 파일함 기능
  src/views/storage/TeamStorage.vue
  src/views/storage/TeamUploadModal.vue
  src/views/team/TeamPage.vue
  src/views/team/TeamProfile.vue
  src/views/team/TeamProfileEdit.vue
Labels: Feat, Frontend

#105 [Fix/#99] navbar 로그인창에서 안 뜨게 수정
  src/App.vue
  src/views/notification/NotificationList.vue
Labels: Fix, Frontend

#106 [Fix/#99] 프로필 수정 시 파일 창 여는 영역 수정
  src/views/profile/ProfileEdit.vue
Labels: Fix, Frontend

#107 [Feat/#99] 프로필, 배경 기본 이미지 변경, 레이아웃 일부 변경
  src/assets/img/default/background.jpg
  src/assets/img/default/background.png
  src/assets/img/default/profile.png
  src/views/chat/components/ChatList.vue
  src/views/chat/components/ChatRoom.vue
  src/views/chat/components/ChatRoomDetails.vue
  src/views/profile/PasswordEdit.vue
  src/views/profile/Profile.vue
  src/views/profile/ProfileCard.vue
  src/views/profile/ProfileDeactivation.vue
  src/views/profile/ProfileEdit.vue
  src/views/social/FriendList.vue
  src/views/social/FriendProfile.vue
  src/views/social/FriendRequest.vue
Labels: Feat, Frontend

#108 [Feat/#99] 알림 카운트 수정, 사이드바 라우트 영역 조정
  src/views/mainpage/Tables.vue
  src/views/navbar/Navbar.vue
Labels: Fix, Frontend

#109 [Feat/#104] schedule
  src/etc/TempCalendar.vue
  src/router/index.js
  src/views/calender/CalenderView.vue
  src/views/calender/components/MonthView.vue
  src/views/mainpage/Tables.vue
  src/views/navbar/Navbar.vue
  src/views/sidenav/SidenavProfile.vue
Labels: Feat, Frontend

#110 [Feat/#80] 팀원 이메일 초대 기능
  src/router/index.js
  src/views/storage/TeamStorage.vue
  src/views/team/TeamInvitePage.vue
  src/views/team/TeamProfile.vue
  src/views/team/TeamProfileEdit.vue
Labels: Feat, Frontend

#111 [Feat/#99] 팀 페이지 레이아웃 수정
  src/views/mainpage/Tables.vue
  src/views/sidenav/SidenavProfile.vue
  src/views/storage/TeamStorage.vue
  src/views/team/TeamPage.vue
  src/views/team/TeamProfile.vue
  src/views/team/TeamProfileEdit.vue
Labels: Feat, Frontend

#114 [Feat/#113] weekly calendar
  src/views/calender/CalenderView.vue
  src/views/calender/components/MonthView.vue
  src/views/calender/components/WeekView.vue
  src/views/mainpage/Tables.vue
  src/views/mainpage/components/Tasks.vue
Labels: Feat, Frontend

#116 [Feat/#113] weekly calendar
  src/views/mainpage/components/AddTask.vue
  src/views/mainpage/components/Tasks.vue
  src/views/sidenav/SidenavProfile.vue
Labels: Feat, Frontend

#117 [Feat/#112] Axios baseUrl 설정
  Dockerfile
  src/main.js
Labels: Feat, Frontend, Refactoring

#119 [Feat/#112] 도커파일, NGINX 설정
  Dockerfile
  nginx.conf
  src/views/chat/ChatView.vue
Labels: Feat, Frontend
