Repository beyond-sw-camp/be08-fin-200OK-CONCENTRIC-frontend, pull requests merged in 2024-11, with the labels that each got.

#120 [Feat/#118] 일정 api 추가, 레이아웃 수정
  src/views/calender/CalenderView.vue
  src/views/calender/components/MonthView.vue
  src/views/calender/components/WeekView.vue
  src/views/chat/ChatView.vue
  src/views/mainpage/components/AddTask.vue
  src/views/mainpage/components/Tasks.vue
Labels: Feat, Frontend

#123 [Feat/#121] detail modal
  src/main.js
  src/views/calender/CalenderView.vue
  src/views/calender/components/MonthView.vue
  src/views/calender/components/WeekView.vue
  src/views/calender/components/viewDetails.vue
  src/views/mainpage/Tables.vue
  src/views/mainpage/components/Tasks.vue
  src/views/sidenav/SidenavProfile.vue
Labels: Feat, Frontend

#124 [Feat/#112] 요청변경
  src/main.js
Labels: Feat, Frontend

#126 feat:일정 상세보기 및 서브태스크 구현
  src/views/calender/components/ViewSubDetails.vue
  src/views/calender/components/viewDetails.vue
Labels: Feat, Frontend

#127 [Feat/#125] 상세보기 창 수정, 권한 없는 사용자 접근 시 alert
  src/views/calender/CalenderView.vue
  src/views/calender/components/ViewSubDetails.vue
  src/views/calender/components/viewDetails.vue
  src/views/chat/ChatView.vue
  src/views/mainpage/components/AddTask.vue
Labels: Feat, Frontend

#129 [Feat/#125] Tasks에서 배경색 추가, 캘린더 해당 팀 일정 보기 추가
  src/views/calender/CalenderView.vue
  src/views/mainpage/components/Tasks.vue
Labels: Feat, Frontend

#130 [Feat/#125] 사이드바 높이 메인 컴포넌트에 의존
  src/views/mainpage/Tables.vue
  src/views/mainpage/components/Tasks.vue
  src/views/team/TeamPage.vue
Labels: Feat, Frontend

#131 [Refactor/#99] 팀페이지 ui 수정
  src/views/team/TeamProfile.vue
Labels: Feat, Frontend

#139 [Refactor/#99] 드롭다운, 팀페이지 수정
  src/views/sidenav/SidenavProfile.vue
  src/views/team/TeamProfile.vue
Labels: Feat, Frontend

#140 [Feat] Frontend workflow
  .github/workflows/frontend.yml
  k8s/frontend-deployment.yaml
Labels: Feat, Frontend

#141 [Fix] Fix workflow
  .github/workflows/frontend.yml
Labels: Fix, Frontend

#142 [Fix] Update frontend.yml
  .github/workflows/frontend.yml
Labels: Fix

#144 [Fix] add artifact
  .github/workflows/frontend.yml
Labels: Fix, Frontend

#143 [Refactor/#135] 팀 초대 변경
  src/views/team/TeamPage.vue
  src/views/team/TeamProfile.vue
Labels: Frontend, Refactoring

#149 [Refactor/#135] 라우터 가드 수정, 팀 초대 수락 페이지, 팀원 내보내기(팀원에겐 안보이도록), navbar 안보일땐 ap…
  src/App.vue
  src/router/index.js
  src/views/navbar/Navbar.vue
  src/views/sidenav/SidenavProfile.vue
  src/views/team/TeamInvitePage.vue
  src/views/team/TeamProfile.vue
  src/views/team/TeamProfileEdit.vue
Labels: Frontend, Refactoring

#150 [Feat/#125] 일정 관련 전반적으로 수정
  src/views/calender/CalenderView.vue
  src/views/calender/components/MonthView.vue
  src/views/calender/components/WeekView.vue
  src/views/mainpage/components/AddTask.vue
  src/views/mainpage/components/Tasks.vue
Labels: Feat, Frontend, Refactoring

#151 [Feat/#125] 일정 수정 완료
  src/views/calender/CalenderView.vue
  src/views/calender/components/MonthView.vue
  src/views/calender/components/WeekView.vue
  src/views/calender/components/viewDetails.vue
  src/views/mainpage/components/Tasks.vue
  src/views/team/TeamProfile.vue
Labels: Feat, Frontend

#155 [Refactor/#154] 스케줄 레이아웃 수정
  src/views/calender/components/MonthView.vue
  src/views/chat/ChatView.vue
  src/views/mainpage/components/AddTask.vue
  src/views/navbar/Navbar.vue
Labels: Feat, Frontend, Refactoring

#156 [Refactor/#99] 파일 위치 정렬 및 그룹원 없을때 기본표시
  src/router/index.js
  src/views/mainpage/Tables.vue
  src/views/storage/TeamUploadModal.vue
  src/views/storage/UploadModal.vue
  src/views/team/TeamPage.vue
  src/views/team/TeamProfile.vue
Labels: Feat, Frontend

#157 [Feat/#153] 비밀번호 초기화 기능 완료
  src/main.js
  src/views/navbar/Navbar.vue
  src/views/profile/Profile.vue
  src/views/sign/findPassword.vue
  src/views/team/TeamProfile.vue
Labels: Feat, Frontend

#159 [Refactor/#158] 웹소켓 중복 구독 문제
  src/views/calender/CalenderView.vue
  src/views/chat/ChatView.vue
  src/views/mainpage/components/Tasks.vue
  src/views/navbar/Navbar.vue
Labels: Fix, Frontend, Refactoring

#161 [Refactor] 알림 드롭 다운 수정
  src/views/navbar/Navbar.vue
  src/views/sign/Signin.vue
Labels: Frontend, Refactoring

#164 [Refactor/#163] css 레이아웃 수정
  src/App.vue
  src/views/calender/CalenderView.vue
  src/views/calender/components/MonthView.vue
  src/views/calender/components/ViewSubDetails.vue
  src/views/calender/components/WeekView.vue
  src/views/chat/ChatView.vue
  src/views/chat/components/ChatList.vue
  src/views/chat/components/ChatRoom.vue
  src/views/chat/components/ChatRoomDetails.vue
  src/views/mainpage/components/AddTask.vue
  src/views/mainpage/components/Tasks.vue
  src/views/navbar/Navbar.vue
  src/views/notification/NotificationList.vue
Labels: Fix, Frontend, Refactoring

#165 [Fix/#163] sockjs 주소 변경
  src/views/chat/ChatView.vue
Labels: Fix, Frontend

#166 [Fix/#163] fix friend profile image
  src/views/social/FriendProfile.vue
Labels: Fix, Frontend

#167 [Fix/#163] 일정 타임존 변경
  src/views/calender/components/MonthView.vue
  src/views/calender/components/WeekView.vue
  src/views/mainpage/components/Tasks.vue
Labels: Fix, Frontend

#168 [Refactor/#163] 타임존 변경에 따른 일정 시간 수정
  src/views/calender/components/MonthView.vue
  src/views/calender/components/WeekView.vue
  src/views/mainpage/components/Tasks.vue
Labels: Fix

#169 [Fix/#163] 타임존 설정
  Dockerfile
Labels: Fix, Frontend

#170 [Fix/#163] 개인 일정이고 기간이 지난 경우와 그냥 기간이 지난 경우 구분
  src/views/mainpage/components/Tasks.vue
Labels: Fix, Frontend
